### ISSUE TITLE
advanced search issue?

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#62] opened 2017-07-17 16:11 UTC
This may just be me not understanding how it works.
I ticked the boxes for Latin and English languages, 14th and 15th cent., England and France origin (the aim was to search with multiple selections from each filter). I didn't get any meaninful results:

http://black01-qa.bodleian.ox.ac.uk/catalog?utf8=%E2%9C%93&op=AND&ms_title_s=&name_s=&f_inclusive%5Bms_lang_sm%5D%5B%5D=Latin&f_inclusive%5Bms_lang_sm%5D%5B%5D=English&f_inclusive%5Bms_date_sm%5D%5B%5D=15th+Century&f_inclusive%5Bms_date_sm%5D%5B%5D=14th+Century&f_inclusive%5Bms_origin_sm%5D%5B%5D=England&f_inclusive%5Bms_origin_sm%5D%5B%5D=France&sort=score+desc%2C+sort_title+asc&search_field=&commit=Search

**Comment by ahankinson** [comment] 2017-07-17 16:19
Yeah, not sure what's going on there. @IgnatG ?

**Comment by IgnatG** [comment] 2017-07-17 19:12
I know where the issue is. I'll push the update tomorrow morning

**Comment by IgnatG** [comment] 2017-07-18 09:15
this should be fixed now. Reopen if it's still not "behaving"

**Closed by IgnatG** 2017-07-18 09:15 UTC
