### ISSUE TITLE
Links to Zotero bibliography broken

### ISSUE THREAD

**Issue by adunning** [bodleian/medieval-mss#304] opened 2020-02-13 14:56 UTC
Links to tags in the Zotero bibliography are broken due to a recent redesign. I have raised this with the developers here:

<https://forums.zotero.org/discussion/81382/linking-to-tags-in-an-online-library>

**Comment by andrew-morrison** [comment] 2020-02-13 15:15
Is this a duplicate of #287 or something new?

**Comment by holfordm** [comment] 2020-02-13 15:49
I think the conversation about changed URLs took place by email rather than here but I think the issue is the same - @adunning do you have examples of links that are currently not working, as our website was reindexed to reflect the new structure of the Zotero URLs and the links should now be working

**Comment by holfordm** [comment] 2020-02-13 16:01
URLs with commas in do not seem to work: e.g. https://www.zotero.org/groups/434020/bodleian_library_western_medieval_manuscripts_bibliography/tags/MSS.%20Bodl.%20272-3,%20289 
(any thoughts as to why?) - otherwise I can't find anything broken atm

**Comment by andrew-morrison** [comment] 2020-02-13 16:09
[url=https://en.wikipedia.org/wiki/Percent-encoding]Percent-encoding[/url] seems to fix it.

**Comment by andrew-morrison** [comment] 2020-02-13 16:22
...but percent encoding the API call to get the number of matches breaks it, annoyingly.

**Comment by andrew-morrison** [comment] 2020-02-13 16:33
Here are the punctuation characters in shelfmarks in the Medieval catalogue, and an example for each:
```
=	Christ Church MS. 344 = Christ Church Archives, D&amp;C vi.c.4
-	MSS. Canon. Misc. 208-9
,	MSS. Bodl. 298, 363-4
;	Christ Church MS. 344 = Christ Church Archives, D&amp;C vi.c.4
/	MS. Gr. class. b. 1 (P)/1-12
.	MS. Canon. Gr. 35
'	MS. D'Orville 516
(	MS. Gr. class. g. 66 (P)
)	MS. Gr. class. f. 82 (P)
[	[pr.] MS. Bodl. 403
]	[pr.] Gough Maps 45, fol. 165
*	MS. Lat. misc. e. 42*
&	Christ Church MS. 344 = Christ Church Archives, D&amp;C vi.c.4
+	Merton College 16. b. 10 + Merton College 24 k. 11
```

**Comment by andrew-morrison** [comment] 2020-02-13 16:37
I've updated QA so that it encodes the tag in the link but not in the API call. Please test it and let me know by the end of Monday if I should deploy the same changes to PRD.

**Comment by andrew-morrison** [comment] 2020-02-18 10:32
I have deployed this change to the production web site. It seems to fix the known issues. I have no way to know when a manuscript lacks a Zotero link whether that is because it doesn't have any references, or there is an issue. Please re-open if you find any problems.

**Closed by andrew-morrison** 2020-02-18 10:32 UTC
