### ISSUE TITLE
Date issues

### ISSUE THREAD

**Issue by andrew-morrison** [bodleian/medieval-mss#104] opened 2017-12-04 12:10 UTC
I'm not sure of the effect on the web site, but the XQuery script that controls what is indexed for manuscripts is looking in the TEI for history/origin/date elements within msDesc and msPart sections, and finding nothing. That means nothing is being indexed in the following Solr fields:

ms_date_stmt_s
ms_date_earliest_i
ms_date_latest_i

Maybe these aren't needed any more anyway? Or the configuration in Blacklight to use them isn't there yet. Either way, it isn't a current problem, but I'm creating this issue to note it for clean up or more development work later.

**Comment by holfordm** [comment] 2017-12-04 14:21
I think that what has happened is that `@notAfter`, `@notBefore` and `@when` were to be used for the date filter, but this was impractical, so @ahankinson created a century filter instead. However I suggest that we retain the indexing of those attributes so that in future an advanced search on date with notBefore and notAFter boxes could be created.

**Comment by andrew-morrison** [comment] 2017-12-08 16:55
Reinstating these fields would do little more than add noise to the index.

Nothing that would be indexed in ms_date_stmt_s isn't already indexed as free text. Even typos, [for example](http://medieval-qa.bodleian.ox.ac.uk/?utf8=%E2%9C%93&f%5Btype%5D%5B%5D=manuscript&q=%2216rh+century%22).

ms_date_earliest_i and ms_date_latest_i appear not to be configured to be indexed by Solr at all.

Therefore I think it would be better to comment these out of the XQuery script, with a note explaining their purpose, so they can be reinstated if a precise date advanced search feature is developed in the future.

What might be useful would be to set up a new index field for `@when` values. That wouldn't index anything new, but it would boost the ranking of manuscripts that have precise years when users search for those years, say if they're looking for anything associated with a key date in history. That is because search engines like Solr favour matches that are entire, or nearly entire, field values. For example, [Searching for 1415](http://medieval-qa.bodleian.ox.ac.uk/?utf8=%E2%9C%93&f%5Btype%5D%5B%5D=manuscript&q=1415) currently returns [MS. Rawl. G. 194](http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_8551) as the 18th best match, but making this change would bring it nearer the top.

**Comment by andrew-morrison** [comment] 2017-12-08 17:35
While investigating this, I found that the XQuery hasn't been including some manuscripts in all the centuries it should in the Century filter, if the `@notAfter` was a turn-of-the-century year. For example...

`<origDate calendar="Gregorian" notAfter="1600" notBefore="1400">15th century and 16th century</origDate>`

...was being indexed as 15th century only. Now it will be included in the 16th century as well.

Another gap was when a `@notAfter` is specified but no `@notBefore`, or vice versa. These cases weren't being included in the Century filter at all. I've changed that so it will be in the century closest to the only known date (e.g. if the creation date is "after 1400" then the 15th century, if "before 1400" then the 14th century.)

In total, these changes have found 660 new centuries associated with `origDate` fields, although quite a lot of manuscripts won't actually change because they have multiple parts, and if one part was missing from one century another part may have covered it.

There are other edge cases that are potentially causing manuscripts to not be counted in centuries they maybe should be, such as examples like this:

`<origDate calendar="Gregorian" notAfter="0700" notBefore="0300">4th century - 7th century (in part)</origDate>`

I assume that means it could've been created any time between 300AD and 700AD? But it will only be included in the Century filter in the 4th and 7th centuries. With some work the XQuery could be made to loop through the intervening centuries and add them all, but then that would be incorrect for examples such as this:

`<origDate calendar="Gregorian" notAfter="1600" notBefore="1040">11th century, middle; added drawing, 16th century (?)</origDate>`

I've spent some time on this because date issues are likely to come up again in pretty much every TEI catalogue. Let me know if I've misunderstood anything. If we can get the code that handles dates as good as it can be then it may be worth splitting that out into a reusable library of date functions.

**Comment by holfordm** [comment] 2017-12-12 13:34
There are some cases where a long date range does indeed mean either "created in the 3rd, 4th, 5th and 6th centuries" or "created at some point in the 3rd-6th century, we don't know when", and in these cases it would be good to index each century (3, 4, 5, 6). 
In other cases a date range is caused by using one `<origDate>` to capture two non-contiguous date events, which we have now deprecated: two or more `<origDate>` should be used. In these cases it would be wrong to index the intervening centuries.
I should correct the markup in these latter cases. If you could pull together a list of all descriptions that contain a date range of more than two centuries (i.e. (notAfter - notBefore) > 200), that would be enormously helpful...

**Comment by andrew-morrison** [comment] 2017-12-12 16:26
OK, using multiple origDate fields for discrete periods when something was added to, over the course of several centuries, makes sense. Out of interest, where would that sort of recommendation be documented?

I can send you a list, but if you're using Oxygen the easiest way to find origDate fields spanning multiple centuries would be to do a File/Replace in Files, setting the _Text to find_ to `.+` with the _Regular expression_ checkbox selected, set the _Scope_ to the path of your local repository, set the _Include files_ to `*.xml`, select the _Recurse directories_ checkbox, and paste the following into _Restrict to XPath_:

`//tei:origin//tei:origDate[(@notAfter/data() - @notBefore/data()) > 200 and not(count(parent::*/origDate) > 1)]`

It should then show you a list with the origDate elements which match displayed, and you can click on the ones that need changing to jump straight to the right point in the files to make the changes.

**Comment by andrew-morrison** [comment] 2017-12-12 18:24
Another issue to be fixed is when the date range straddles the year 1 AD (but there are currently only four examples of this.)

**Comment by andrew-morrison** [comment] 2017-12-13 15:03
There are also 17 instances where the `@notBefore` is later than the `@notAfter`. You can find them the same way using this XPath:

`//tei:origin//tei:origDate[@notAfter/data() < @notBefore/data() and @notAfter/data() > 0]`

**Comment by holfordm** [comment] 2017-12-13 16:07
We should add a schematron rule to catch this

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by andrew-morrison** [comment] 2017-12-14 10:12
I think the XQuery now handles all origDates as it should. [Attached is a chart](https://github.com/bodleian/medieval-mss/files/1558649/date_issues.pdf) showing the difference made by the above code fixes, and the latest updates made to the TEI, on the Century filter.

Notable is that the 1st and 2nd BCE have gone down, but I believe this is correct. The old code was regarding something like this...

`<origDate calendar="Gregorian" notAfter="-0200" notBefore="-0300">3rd century BC</origDate>`

...as belonging to both the 3rd and the 2nd centuries BCE. Now it only includes them in the 3rd century BCE, matching the text description, and consistent with the behaviour for CE date ranges.

Also fixed are a few other edge cases, like the four manuscripts whose origin could be either side of the divide, which you can now [find by selecting both first centuries](http://medieval-qa.bodleian.ox.ac.uk/?f%5Bms_date_sm%5D%5B%5D=1st+Century+BCE&f%5Bms_date_sm%5D%5B%5D=1st+Century&f%5Btype%5D%5B%5D=manuscript).

**Comment by holfordm** [comment] 2018-01-26 11:44
Seems ok to close this now

**Closed by holfordm** 2018-01-26 11:44 UTC
