### ISSUE TITLE
split authority files?

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#285] opened 2020-01-20 12:44 UTC
Currently we have single authority files for persons, works, places, which has advantages and disadvantages. The main disadvantage is that it makes collaborating on authority file creation harder because of the potential for version conflicts. Collaboration is more likely as work with Cambridge and the colleges expands and because we now have additional medievalist (@adunning) who will be working on the catalogue regularly.
Splitting the files to create one file per authority record (inside directories for persons, places, works, perhaps) would make collaboration easier. It would also enable better tracking of changes to individual authority records. 
So is splitting a good idea?

**Comment by andrew-morrison** [comment] 2020-01-21 10:35
That would mean replacing what are currently three files with ~18,000 separate files. Each would have to have their own TEI schema declarations and header. So more storage. I think GitHub will only display 1000 files per directory in its web interface, but I don't know if that's used very much. It'd slow down the indexing scripts slightly. It might slow down Oxygen too.

Also it wouldn't solve the problem of conflicts entirely. If two people create or edit the same entry at roughly the same time, it'd still create a conflict, whether in its own file or the middle of a file containing a thousand other entries. That conflict would still break the re-indexing. It might make it a little easier for the script to report back where the problem is. Single files would remove the small chance of incidental conflicts when two adjacent entries are edited (because Git is line-by-line based, not XML-aware) but adding more blank lines between each entry would also work.

Some other options for breaking up large and unwieldy authority files include:

 * Split them up by theme, preferably ones with no chance of overlaps (e.g. split the person authority file by birth century, the places one by current country, works by mainLang?)
 * Give each medievalist working on the catalogue their own set of three authority files (but that is somewhat contrary to the point of an authority file, and would probably lead to duplicates.) 
 * Have a "base" file containing all the entries so far, but start adding new ones to an "additions" file, for later review by someone who takes on the role of editor (which is precisely the set up for [Fihrist](https://github.com/fihristorg/fihrist-mss/tree/master/authority), but unless/until funding for editors is found, it's not really working as intended.)

**Comment by andrew-morrison** [comment] 2020-01-21 10:39
Note, as well as the indexing scripts here, I'd have to modify the [ones for the MMM project](https://github.com/mapping-manuscript-migrations/bodleian-mmm).

**Comment by ahankinson** [comment] 2020-01-21 13:43
I'm in agreement with @andrew-morrison -- I don't think splitting the authority files into a single file for each record is a scalable solution. 

The authority files themselves were a bit of a 'hack' on the original idea of the TEI catalogue, when we realized that to get stable URLs we needed to have a consistent source of identity for these records. I do remember there were other tools being proposed, but the TEI XML seemed to be the one with the least overhead and maintenance. Other solutions included bespoke authority databases. 

Ideally, we would be able to share authorities with the central Aleph catalogue team, but I am not sure how likely that would be to happen, and whether it would be useful -- Our TEI catalogue has authorities for provenance entries as well as 'creators', and I don't know if creating those sorts of authorities would fly. It also does not contain authorities for other types of material (places, works, etc.) so it may be a half-measure solution anyway.

It may also be that we could use ArchivesSpace for authorities, but again -- I'm not sure how that would work, or if that would be possible. It would also mean 'harvesting' from ArchivesSpace every time we do a re-index of the data.

To address the problem of conflicts, there are accessible techniques workflows for git, along with several friendly user interfaces, that make the likelihood of conflicts less, and provide you with techniques for resolving them when they do occur. The nomenclature of git is usually the biggest barrier; once that's understood, the workflows generally become second nature. I would be happy to help guide you towards some resources for this.

**Comment by andrew-morrison** [comment] 2020-01-21 14:26
ArchivesSpace has no concept of work authorities. Some discussion and development work would be required to make it work for the other type of authorities, but it is technically possible.

**Comment by adunning** [comment] 2020-01-21 16:07
We've also realized that we need to prepare for integrated authorities with the FAMOUS project, which will involve the development of seals and charters catalogues.

I'm surveying colleagues to see how others are managing this. Two interesting examples are [MEI](https://data.cerl.org/mei/) (Bodleian and CERL, much of this also applicable to manuscripts) and [Biblissima authorities](https://data.biblissima.fr/) (an independent semanitic wiki database). I'm not sure what the new [OCLC Entity Management Infrastructure](https://www.oclc.org/en/news/releases/2020/20200109-oclc-awarded-mellon-grant-linked-data-management-infrastructure.html) is designed to cover or how we might contact them.

If we can manage it, it would be brilliant to use NACO directly to match Aleph cataloguing.

If that cannot be made to work, to build on @ahankinson's idea on ArchivesSpace, what if we used Wikidata? It encompasses everything we would want, and indeed is already one of our data sources, though its work authorities need improvement. Its key advantages are the ease with which anyone can add a new record (a particular bottleneck in cataloguing right now), its multilingual structure, and its references to other authorities.

We could theoretically have cataloguers include Wikidata references directly, in a form such as this:

```xml
<name ref="https://www.wikidata.org/wiki/Q82133">Bodleian Library</name>
```

[We could then eliminate `<persName>`, `<orgName>`, etc., because that could be determined from the entry. Placing the full URI within the entry would make it easier to check, since Oxygen turns it into a link.]

We could then possibly fit this into the existing infrastructure by creating a script that would collect these references from the XML and automatically generate `persons.xml`, `places.xml`, and `works.xml` as a cached version of the Wikidata entries.

Notionally one could do something similar with NACO, but it's not clear to me that we could have new entries created quickly enough or that we would have the capacity to do so.

**Closed** 2021-12-17 11:52 UTC
Labels: question
