### ISSUE TITLE
links to digital bodleian should open in a new window / tab

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#163] opened 2018-07-18 08:43 UTC
## Detailed Description
Due to the way that Digital Bodleian redirects from the 'object' URL to the 'first page' URL (I think), it is difficult to navigate back from Digital Bodleian to the catalogue record. Also, we can probably assume that users will want to flip from DB to the catalogue, so having them in separate tabs by default ought to be most convenient.
@andrew-morrison  not sure if this is an issue for you or @IgnatG

**Comment by andrew-morrison** [comment] 2018-07-18 09:31
Closing as a near-duplicate of #164

**Closed** 2018-07-18 09:32 UTC
